language: cpp
compiler:
- g++
os:
- linux
install:
 # cppcheck
 - sudo apt-get install -qq cppcheck 
branches:
  only:
  - master
script:
 - cd Code
 - make
 # cppcheck
 - cppcheck --quiet --error-exitcode=1 .
 # testing
 - ./parser 
notifications:
  email: false
